# Generated by Django 3.1.7 on 2021-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, null=True, verbose_name='Creado en')),
                ('end_date', models.DateField(auto_created=True, null=True, verbose_name='Fecha Fin')),
                ('start_date', models.DateField(auto_created=True, null=True, verbose_name='Fecha Inicio')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='Descripción')),
                ('recipient_care', models.CharField(choices=[('0', 'Para mi'), ('1', 'Abuelo'), ('2', 'Abuela'), ('3', 'Madre'), ('4', 'Padre'), ('5', 'Hijo'), ('6', 'Hija'), ('7', 'Familiar'), ('7', 'Conocido')], max_length=50, null=True, verbose_name='Destinatario')),
                ('patient_gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True, verbose_name='Género de Paciente')),
                ('patient_phone', models.CharField(max_length=20, null=True, verbose_name='Teféfono del Paciente')),
                ('patient_address', models.CharField(max_length=15, null=True, verbose_name='Dirección del Paciente')),
                ('patient_age', models.IntegerField(null=True, verbose_name='Edad del Paciente')),
                ('salary_min', models.IntegerField(null=True, verbose_name='Salario Mínimo')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Salario Máximo')),
                ('status', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo'), ('2', 'Contratado'), ('5', 'Pendiente')], default=1, max_length=20, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['description'],
            },
        ),
    ]
