# Generated by Django 3.1.7 on 2021-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210313_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(auto_created=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(auto_created=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
