# Generated by Django 3.1.7 on 2021-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210313_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='patient_gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True, verbose_name='Género de Paciente'),
        ),
    ]
