# Generated by Django 3.1.7 on 2021-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión'),
        ),
    ]
