# Generated by Django 3.1.7 on 2021-03-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='title',
        ),
    ]
