# Generated by Django 3.1.7 on 2021-03-14 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_description_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_remove_jobs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('start_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('study', models.CharField(max_length=30)),
                ('caregiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
            ],
        ),
    ]
