# Generated by Django 3.1.7 on 2021-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210314_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='end_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='start_date',
            field=models.DateField(auto_created=True),
        ),
    ]
