# Generated by Django 3.1.7 on 2021-03-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210314_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
