# Generated by Django 3.1.7 on 2021-03-13 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210311_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Creado en')),
                ('end_date', models.DateTimeField(auto_created=True, verbose_name='Fecha Fin')),
                ('start_date', models.DateTimeField(auto_created=True, verbose_name='Fecha Inicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('recipient_care', models.CharField(choices=[('0', 'Para mi'), ('1', 'Abuelo'), ('2', 'Abuela'), ('3', 'Madre'), ('4', 'Padre'), ('5', 'Hijo'), ('6', 'Hija'), ('7', 'Familiar'), ('7', 'Conocido')], max_length=50, null=True, verbose_name='Destinatario')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Teféfono Paciente')),
                ('patient_address', models.CharField(max_length=15, verbose_name='Dirección Paciente')),
                ('patient_age', models.IntegerField(verbose_name='Edad Paciente')),
                ('salary_min', models.IntegerField(verbose_name='Salario Mínimo')),
                ('salary_max', models.IntegerField(blank=True, verbose_name='Salario Máximo')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado en')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['description'],
            },
        ),
    ]
