# Generated by Django 3.1.7 on 2021-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210313_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='service_category',
            field=models.ManyToManyField(to='users.Service'),
        ),
    ]
