# Generated by Django 3.1.7 on 2021-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210313_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='patient_address',
            field=models.CharField(max_length=15, verbose_name='Dirección del Paciente'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='patient_age',
            field=models.IntegerField(verbose_name='Edad del Paciente'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='patient_phone',
            field=models.CharField(max_length=20, verbose_name='Teféfono del Paciente'),
        ),
    ]
