# Generated by Django 3.1.7 on 2021-03-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210313_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo'), ('2', 'Contratado'), ('5', 'Pendiente')], default=1, max_length=20, verbose_name='Estado'),
        ),
    ]
