# Generated by Django 3.1.7 on 2021-03-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210313_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
