# Generated by Django 3.1.7 on 2021-03-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
