# Generated by Django 3.1.7 on 2021-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description_profile',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre mi'),
        ),
    ]
