# Generated by Django 3.1.7 on 2021-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='caregiver_id',
        ),
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(to='users.School'),
        ),
    ]
