# Generated by Django 3.1.7 on 2021-03-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210314_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schools',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
