# Generated by Django 3.1.7 on 2021-03-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='caregiver_id',
            new_name='user_id',
        ),
    ]
