# Generated by Django 3.1.7 on 2021-03-15 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210315_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('employer', models.CharField(max_length=30)),
                ('work_title', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('job_description', models.CharField(max_length=150)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
