# Generated by Django 3.1.7 on 2021-03-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_works'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
