# Generated by Django 3.1.7 on 2021-03-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210315_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='employer',
            field=models.CharField(max_length=30, verbose_name='Empleador'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(auto_created=True, verbose_name='Fecha Finalización'),
        ),
        migrations.AlterField(
            model_name='work',
            name='job_description',
            field=models.CharField(max_length=150, verbose_name='Descripción del Cargo'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_title',
            field=models.CharField(max_length=30, verbose_name='Cargo'),
        ),
    ]
