# Generated by Django 3.1.7 on 2021-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210315_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(verbose_name='Fecha Finalización'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
