# Generated by Django 3.1.7 on 2021-03-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210315_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='job_description',
            field=models.TextField(verbose_name='Descripción del Cargo'),
        ),
    ]
